stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building the project..."
    
deploy_to_github:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache git rsync openssh
    - git config --global user.name "LifeVerse-Game"
    - git config --global user.email "lifeversegame@gmail.com"
  script:
    - git clone --depth 1 https://oauth2:${GITHUB_TOKEN}@github.com/LifeVerse-Game/API.git target-repo
    - rsync -av --exclude='.git' ./API/ target-repo/
    - cd target-repo
    - git add .
    - git commit -m "Automated deployment from GitLab CI/CD"
    - git push origin main
  only:
    - main
